DEFAULT_CATEGORIES = [
    "Policy",
    "Claims",
    "Underwriting",
    "Financial",
    "Legal",
    "Correspondence",
]

DEFAULT_SUBCATEGORIES: dict[str, list[str]] = {
    "Policy": [
        "Auto Policy",
        "Home / Property Policy",
        "Health Policy",
        "Life Policy",
        "Commercial / Business Policy",
        "Liability Policy",
        "Workers Compensation",
        "Other",
    ],
    "Claims": [
        "Claim Form",
        "Medical Records",
        "Police / Incident Report",
        "Adjuster Report",
        "Settlement Agreement",
        "Proof of Loss",
        "Damage Photos",
        "Other",
    ],
    "Underwriting": [
        "Application Form",
        "Risk Assessment",
        "Inspection Report",
        "Loss History / Loss Run",
        "Questionnaire",
        "Other",
    ],
    "Financial": [
        "Premium Invoice",
        "Payment Receipt",
        "Loss Run Report",
        "Financial Statement",
        "Audit Report",
        "Other",
    ],
    "Legal": [
        "Endorsement",
        "Rider / Amendment",
        "Exclusion Notice",
        "Contract / Agreement",
        "Power of Attorney",
        "Subrogation Letter",
        "Other",
    ],
    "Correspondence": [
        "Cancellation Notice",
        "Renewal Notice",
        "Demand Letter",
        "Coverage Update",
        "Declination Letter",
        "Other",
    ],
}
